/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import Calculos.Mediana;

/**
 *
 * @author PYU
 */
public class JFCalculoMediana extends javax.swing.JFrame {

    /**
     * Creates new form JFCalculoMedia
     */
    Mediana l = new Mediana();

    public JFCalculoMediana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPCalculoMediana = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNumerosDigitados = new javax.swing.JTextArea();
        jTextFieldMediana = new javax.swing.JTextField();
        jButtonAddNumero = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldgetNumero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calcular Mediana");

        jTextAreaNumerosDigitados.setEditable(false);
        jTextAreaNumerosDigitados.setColumns(20);
        jTextAreaNumerosDigitados.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextAreaNumerosDigitados.setRows(5);
        jScrollPane1.setViewportView(jTextAreaNumerosDigitados);

        jTextFieldMediana.setEditable(false);
        jTextFieldMediana.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N

        jButtonAddNumero.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jButtonAddNumero.setText("Adicionar");
        jButtonAddNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNumeroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jLabel1.setText("A mediana dessa sequencia é :");

        jTextFieldgetNumero.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N

        javax.swing.GroupLayout JPCalculoMedianaLayout = new javax.swing.GroupLayout(JPCalculoMediana);
        JPCalculoMediana.setLayout(JPCalculoMedianaLayout);
        JPCalculoMedianaLayout.setHorizontalGroup(
            JPCalculoMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCalculoMedianaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(JPCalculoMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPCalculoMedianaLayout.createSequentialGroup()
                        .addComponent(jTextFieldgetNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(jButtonAddNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPCalculoMedianaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(JPCalculoMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldMediana))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        JPCalculoMedianaLayout.setVerticalGroup(
            JPCalculoMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCalculoMedianaLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(JPCalculoMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldgetNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jTextFieldMediana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPCalculoMediana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPCalculoMediana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNumeroActionPerformed
        l.inserirMediana(Float.parseFloat(jTextFieldgetNumero.getText()));
        if (l.getContagemElementos() == 1) {
            jTextFieldMediana.setText(l.retornaElemento(1).toString());
            jTextAreaNumerosDigitados.append(jTextFieldgetNumero.getText());
            jTextFieldgetNumero.setText(null);
            return;
        }

        if (l.getContagemElementos() > 1) {
            jTextAreaNumerosDigitados.append("," + jTextFieldgetNumero.getText());
            jTextFieldMediana.setText(null);
        } else {
            jTextAreaNumerosDigitados.append(jTextFieldgetNumero.getText());
        }
        if ((l.getContagemElementos() % 2) == 1) {
            Float aux = (l.retornaElemento((l.getContagemElementos() + 1) / 2));
            jTextFieldMediana.setText(aux.toString());
        } else {
        Float aux = (l.retornaElemento((l.getContagemElementos() / 2), ((l.getContagemElementos() / 2) + 1)));
            jTextFieldMediana.setText(aux.toString());
        }

        jTextFieldgetNumero.setText(null);


    }//GEN-LAST:event_jButtonAddNumeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCalculoMediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCalculoMediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCalculoMediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCalculoMediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCalculoMediana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPCalculoMediana;
    private javax.swing.JButton jButtonAddNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaNumerosDigitados;
    private javax.swing.JTextField jTextFieldMediana;
    private javax.swing.JTextField jTextFieldgetNumero;
    // End of variables declaration//GEN-END:variables
}
