/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.JOptionPane;

/**
 *
 * @author PYU
 */
public class JFHome extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public JFHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBMedidas_de_tendencia_central = new javax.swing.JButton();
        jBseries_estatisticas = new javax.swing.JButton();
        jBDistribuicao_de_frequencia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBReferências = new javax.swing.JButton();
        jBMedidas_separatrizes = new javax.swing.JButton();
        jBSobre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Probabilidade Estatística");
        setResizable(false);

        jBMedidas_de_tendencia_central.setText("Medidas de Tendência Central");
        jBMedidas_de_tendencia_central.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMedidas_de_tendencia_centralActionPerformed(evt);
            }
        });

        jBseries_estatisticas.setText("Séries Estatísticas");
        jBseries_estatisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBseries_estatisticasActionPerformed(evt);
            }
        });

        jBDistribuicao_de_frequencia.setText("Distribuição de Frequência");
        jBDistribuicao_de_frequencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDistribuicao_de_frequenciaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 30)); // NOI18N
        jLabel1.setText("Calculadora Estatística");

        jBReferências.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBReferências.setText("Referências");
        jBReferências.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReferênciasActionPerformed(evt);
            }
        });

        jBMedidas_separatrizes.setText("Medidas Separatrizes");
        jBMedidas_separatrizes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMedidas_separatrizesActionPerformed(evt);
            }
        });

        jBSobre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBSobre.setText("Sobre");
        jBSobre.setPreferredSize(new java.awt.Dimension(127, 23));
        jBSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSobreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(192, 192, 192))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBMedidas_de_tendencia_central, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                        .addGap(60, 60, 60)
                        .addComponent(jBMedidas_separatrizes, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBseries_estatisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jBDistribuicao_de_frequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jBReferências, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBMedidas_de_tendencia_central, jBMedidas_separatrizes});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBDistribuicao_de_frequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBseries_estatisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBMedidas_de_tendencia_central, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMedidas_separatrizes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBReferências, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBMedidas_de_tendencia_centralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMedidas_de_tendencia_centralActionPerformed
        JFMdt jfMDT = new JFMdt();
        jfMDT.setLocationRelativeTo(null);
        jfMDT.setVisible(true);
    }//GEN-LAST:event_jBMedidas_de_tendencia_centralActionPerformed

    private void jBseries_estatisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBseries_estatisticasActionPerformed
        JFseries_estatísticas jfSE = new JFseries_estatísticas();
        jfSE.setLocationRelativeTo(null);
        jfSE.setVisible(true);
    }//GEN-LAST:event_jBseries_estatisticasActionPerformed

    private void jBDistribuicao_de_frequenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDistribuicao_de_frequenciaActionPerformed
        JFDistribuicao_de_frequencia jfDF = new JFDistribuicao_de_frequencia();
        jfDF.setLocationRelativeTo(null);
        jfDF.setVisible(true);
    }//GEN-LAST:event_jBDistribuicao_de_frequenciaActionPerformed

    private void jBReferênciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReferênciasActionPerformed
      JFReferencia jb = new JFReferencia();
      jb.setLocationRelativeTo(null);
      jb.setVisible(true);

        //JOptionPane.showMessageDialog(null, "\nUNITINS - Sistemas de Informação\nAlunos: \nPatricia Áires\nNilvan Lopes\nVinicius Vicco\nSamuel Da Silva\n\n"
        //        + "Fontes: support.minitab.com/pt-br/minitab/17/topic-library/basic-statistics-and-graphs\n"
        //        + "uff.br/cdme/distfreq/distfreq-html/dfreqcont.html");
    }//GEN-LAST:event_jBReferênciasActionPerformed

    private void jBMedidas_separatrizesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMedidas_separatrizesActionPerformed
        JFMedidasSeparatrizes jf = new JFMedidasSeparatrizes();
        jf.setLocationRelativeTo(null);
        jf.setVisible(true);
    }//GEN-LAST:event_jBMedidas_separatrizesActionPerformed

    private void jBSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSobreActionPerformed
        JFSobre jfsobre = new JFSobre();
        jfsobre.setLocationRelativeTo(null);
        jfsobre.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFHome JFHome = new JFHome();
                JFHome.setLocationRelativeTo(null);
                JFHome.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDistribuicao_de_frequencia;
    private javax.swing.JButton jBMedidas_de_tendencia_central;
    private javax.swing.JButton jBMedidas_separatrizes;
    private javax.swing.JButton jBReferências;
    private javax.swing.JButton jBSobre;
    private javax.swing.JButton jBseries_estatisticas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
