/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author PYU
 */
public class JFMediana extends javax.swing.JFrame {

    /**
     * Creates new form JFMedia
     */
    public JFMediana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMediana = new javax.swing.JPanel();
        jLabelMediana = new javax.swing.JLabel();
        jScrollPaneMedia = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButtonCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Medidas de Tendência Central");

        jLabelMediana.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 20)); // NOI18N
        jLabelMediana.setForeground(new java.awt.Color(51, 0, 204));
        jLabelMediana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMediana.setText("Mediana");

        jScrollPaneMedia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("\tUse a mediana para descrever um conjunto inteiro de observações com um \núnico valor representando o centro dos dados. Metade das observações estão acima da \nmediana e metade abaixo. Isso é determinado classificando-se os dados e localizando a \nobservação número [N + 1] / 2.\n\tSe o número de observações é par, a mediana é extrapolada como o valor \nentre a observação N / 2 e [N / 2] + 1.\n\n\t7,9,10,12,13,14,17,18,19\n \nPara esses dados ordenados, a mediana é 13. Ou seja, 50% dos valores são menores \nque ou iguais a 13 e 50% dos valores são maiores que ou iguais a 13.\n");
        jScrollPaneMedia.setViewportView(jTextArea2);

        jButtonCalcular.setText("Calcular Mediana");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMedianaLayout = new javax.swing.GroupLayout(jPanelMediana);
        jPanelMediana.setLayout(jPanelMedianaLayout);
        jPanelMedianaLayout.setHorizontalGroup(
            jPanelMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMedianaLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanelMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMedianaLayout.createSequentialGroup()
                        .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(339, 339, 339))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMedianaLayout.createSequentialGroup()
                        .addComponent(jScrollPaneMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
            .addGroup(jPanelMedianaLayout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jLabelMediana)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelMedianaLayout.setVerticalGroup(
            jPanelMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMedianaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelMediana)
                .addGap(30, 30, 30)
                .addComponent(jScrollPaneMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMediana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMediana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        JFCalculoMediana jFCalculoMediana = new JFCalculoMediana();
        jFCalculoMediana.setLocationRelativeTo(null);
        jFCalculoMediana.setVisible(true);
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMediana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JLabel jLabelMediana;
    private javax.swing.JPanel jPanelMediana;
    private javax.swing.JScrollPane jScrollPaneMedia;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
