/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author PYU
 */
public class JFModa extends javax.swing.JFrame {

    /**
     * Creates new form JFMedia
     */
    public JFModa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMedia = new javax.swing.JPanel();
        jLabelMedia = new javax.swing.JLabel();
        jScrollPaneMedia = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButtonCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Medidas de Tendência Central");

        jLabelMedia.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 20)); // NOI18N
        jLabelMedia.setForeground(new java.awt.Color(51, 0, 204));
        jLabelMedia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMedia.setText("Moda");

        jScrollPaneMedia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("\tA moda é o valor que ocorre mais frequentemente em um conjunto de observações. A moda pode ser usada com a média e a mediana para fornecer uma caracterização geral da distribuição dos dadosEnquanto a média e a mediana exigem um cálculo, a moda é encontrada simplesmente contando-se o número de vezes que cada valor ocorre em um conjunto de dados.\n\tIdentificar a moda pode ajudar a entender a distribuição. Uma distribuição com mais de uma moda pode indicar que a amostra foi coletada de uma população mista. Por exemplo, você pode ter colet  do dados de tempo de espera para clientes que estão descontando cheques e clientes que estão pedindo hipotecas. Para entender melhor os dados, esses dois casos deveriam ser coletados separadamente. Quando existe mais de duas modas, a distribuição é multimodal.\n\n\tMonomodal\n Exemplo: 1,4,8,8,8,9,4,1.\nExiste somente uma moda, 8, que ocorre com mais frequência.\n\n\tBimoda\nExemplo: 7,4,4,12,34,16,17,16,16,4l\nExistem dois modos, 4 e 16. Os dados parecem representar duas populações diferentes.\n");
        jScrollPaneMedia.setViewportView(jTextArea2);

        jButtonCalcular.setText("Calcular Moda");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMediaLayout = new javax.swing.GroupLayout(jPanelMedia);
        jPanelMedia.setLayout(jPanelMediaLayout);
        jPanelMediaLayout.setHorizontalGroup(
            jPanelMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMediaLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jScrollPaneMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jPanelMediaLayout.createSequentialGroup()
                .addGroup(jPanelMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMediaLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMediaLayout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(jLabelMedia)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMediaLayout.setVerticalGroup(
            jPanelMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMediaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelMedia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        JFCalculoModa jFCalculoModa = new JFCalculoModa();
        jFCalculoModa.setLocationRelativeTo(null);
        jFCalculoModa.setVisible(true);
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFModa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFModa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFModa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFModa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFModa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JLabel jLabelMedia;
    private javax.swing.JPanel jPanelMedia;
    private javax.swing.JScrollPane jScrollPaneMedia;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
