/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Calculos.mtc;
import java.util.Collections;
import java.util.LinkedList;

/**
 *
 * @author Samuel S. Morais
 */
public class TabelaDiscreta extends javax.swing.JFrame {

    /**
     * Creates new form Tabela
     */
    public TabelaDiscreta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        mtcList = new LinkedList<mtc>();
        jTextXi = new javax.swing.JTextField();
        jTextFi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        add = new javax.swing.JButton();

        mtcList = org.jdesktop.observablecollections.ObservableCollections.observableList(mtcList);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextXi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextXiActionPerformed(evt);
            }
        });

        jTextFi.setToolTipText("");

        jLabel1.setText("Xi");

        jLabel2.setText("Fi");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, mtcList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${xi}"));
        columnBinding.setColumnName("Xi");
        columnBinding.setColumnClass(double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fi}"));
        columnBinding.setColumnName("Fi");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fr}"));
        columnBinding.setColumnName("Fr");
        columnBinding.setColumnClass(Double.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fac}"));
        columnBinding.setColumnName("Fac");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fiacr}"));
        columnBinding.setColumnName("Fiacr");
        columnBinding.setColumnClass(Double.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        add.setText("adicionar");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextXi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(add)
                .addContainerGap(119, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextXi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextFi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextXiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextXiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextXiActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        mtc m;
        String xitext = jTextXi.getText();
        double xi;
        int fi;
        xitext = xitext.replace(",",".");
        xi = Double.parseDouble(xitext);
        fi =Integer.valueOf(jTextFi.getText());
        m= new mtc(xi,fi);
        if(verificaXi(m))
            mtcList.add(m);
        Collections.sort(mtcList); 
        int linhaAtual = 0;
        
    int linhaFinal = jTable1.getRowCount()-1;
         do{
                fac(linhaAtual);
                linhaAtual++;
        }while(linhaAtual<=linhaFinal);
          linhaAtual = 0;
                  do{
              fr(linhaAtual);
                Fiacr(linhaAtual);
                linhaAtual++;
                 }while(linhaAtual<=linhaFinal);
    }//GEN-LAST:event_addActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseClicked
   
      public boolean verificaXi(mtc testa) {
        for (mtc e : mtcList) {
            if (testa.getXi() == e.getXi()) {
                adicionaFi(testa);
                return false;
            }
        }
        return true;
    }

     public void adicionaFi(mtc m) {
        for (mtc e : mtcList) {
            if (m.getXi() == e.getXi()) {
                e.setFi(m.getFi() + e.getFi());
            }
        }

    }
    public void fac(int row){
        mtc   m;
        mtc   m2;
        int     total;
        m=mtcList.get(row);
        if(row>0){
                m2 = mtcList.get(row-1);
                total = m.getFi()+ m2.getFac();
        }
        else
                total = m.getFi();
        m.setFac(total);
    }
    
    public void fr(int row){
        mtc   m;
        mtc   m2;
        double     total;
        m=mtcList.get(row);
        double fiAtual= m.getFi();
        int n = jTable1.getRowCount()-1;
        if(n>0){
               
                m2=mtcList.get(n);
                double somatorio = m2.getFac();
                total = (fiAtual*100) / somatorio;
                  
        }
        else
                total = 100;
        m.setFr(total);  
        System.out.println(m.getXi() + " é " + m.getFr());
    }
    
    public void Fiacr(int row){
        mtc  m;
        mtc  m2;
        double total;
        m=mtcList.get(row);
        int n = jTable1.getRowCount()-1;
        if(row==0){
               total = m.getFr();  
        }
        else{
                m2=mtcList.get(row-1);
                total = m.getFr()+ m2.getFiacr();
        }
        m.setFiacr(total);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaDiscreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaDiscreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaDiscreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaDiscreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaDiscreta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFi;
    private javax.swing.JTextField jTextXi;
    private java.util.List<mtc> mtcList;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
